In [170]:
import pandas as pd

In [171]:
data = pd.read_csv('../data/raw/Madrid_aproperties.csv')
data

,heading,location,content,id,area,n_bedrooms,n_bathrooms,Price
0,Flat for sale in calle Treviño (Madrid),"Nuevos Ministerios - Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,34 m2,1.0,1.0,"€ 287,000"
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,187-207 m2,NaN,NaN,"from € 2,917,000"
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,49 m2,1.0,1.0,"€ 450,000"
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,148 m2,3.0,4.0,"€ 2,500,000"
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,101 m2,2.0,2.0,"€ 1,359,000"
...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,399 m2,6.0,5.0,"€ 2,500,000"
938,Luminous house with terrace for sale in Conde ...,"Conde Orgaz - Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,750 m2,6.0,7.0,"€ 3,100,000"
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Conde Orgaz - Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,"1,320 m2",5.0,8.0,"€ 3,375,000"
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,480 m2,4.0,4.0,"€ 1,750,000"
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,848 m2,9.0,7.0,"€ 5,800,000"

In [172]:
data.shape

(942, 8)

In [173]:
data.drop_duplicates()

,heading,location,content,id,area,n_bedrooms,n_bathrooms,Price
0,Flat for sale in calle Treviño (Madrid),"Nuevos Ministerios - Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,34 m2,1.0,1.0,"€ 287,000"
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,187-207 m2,NaN,NaN,"from € 2,917,000"
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,49 m2,1.0,1.0,"€ 450,000"
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,148 m2,3.0,4.0,"€ 2,500,000"
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,101 m2,2.0,2.0,"€ 1,359,000"
...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,399 m2,6.0,5.0,"€ 2,500,000"
938,Luminous house with terrace for sale in Conde ...,"Conde Orgaz - Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,750 m2,6.0,7.0,"€ 3,100,000"
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Conde Orgaz - Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,"1,320 m2",5.0,8.0,"€ 3,375,000"
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,480 m2,4.0,4.0,"€ 1,750,000"
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,848 m2,9.0,7.0,"€ 5,800,000"

In [174]:
data.value_counts()

heading                                        location                                      content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id          area      n_bedrooms  n_bathrooms  Price
Flat for sale in Príncipe de Vergara.          Castellana, Madrid city                       In the emblematic Barrio de Salamanca, calle Príncipe Vergara, you have 271 m2 and 28 m2 of terrace.\n\nperfect for investment with very good profitability with private terrace, it has 271 m2 and 28 m2 of terrace, in representative property of great beauty.\n\nIt has 6 bedrooms, bathroom, kitchen, interior patio for private use and a large storage room in the property itself. It has air conditioning, central heating, porter service and lift.\n\nCan you imagine living here?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      VM2312004   284 m2    6.0         1.0          € 1,700,000    10
Flat for sale in José Abascal street.          Nuevos Ministerios - Ríos Rosas, Madrid city  FLAT WITH TERRACE, FIREPLACE AND GAMES ROOM.\n\nLocated in the neighborhood of Nuevos Ministerios - Ríos Rosas, close to Paseo de la Castellana, between Zurbano and Plaza de Gregorio Marañón, five minutes walk from Serrano and Velázquez, is located this impressive 596 m² property. The flat has a spacious entrance hall and distributor. The day area consists of three living rooms connected by sliding doors. The main living room has a fireplace and a large terrace of 20 m², as well as a large dining room and a guest toilet. The service area has direct access and kitchen, office, pantry, dining room, two large corridors with fitted closets and cupboards and a bedroom with bathroom for the service. In the night area has four bedrooms of which the master bedroom is en suite with a large dressing room and marble bathroom; another with en suite bathroom and two more sharing a bathroom and a games room or gym with window to patio lights; all connected by a corridor with windows to patio block also with leaded windows. The house has central heating by Natural Gas, air conditioning. The flat has an impressive marble spiral staircase, elevator and freight elevator, the property also has a large garage, storage room attached to the property and another storage room on the roof.\n\nCan you imagine living here?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              VM2210011   596 m2    4.0         5.0          € 3,300,000    10
Flat for sale in Preciados.                    Sol, Madrid city                              REFURBISHED EXTERIOR FLAT IN SOL.\n\nSpectacular exterior flat with views to Preciados street. The property is located in an early 20th century building with lift. Designer refurbishment with custom-made furniture, wood finishes and excellent LED lighting. The property is distributed in a spacious and bright living-dining room, with two windows overlooking Preciados street. Fully equipped integrated kitchen, with top of the range appliances. Relaxation area with sofas and flat screen TV. Two bedrooms with en-suite bathrooms. One of the bedrooms with an elegant dressing room/walk-in wardrobe.\n\nThe property has air conditioning and individual heating.\n\nIdeal as an investment product or private home.\n\nCan you imagine living here?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             VM2208018   84 m2     2.0         2.0          € 819,000      10
House for sale in Club de Golf.                Club de Golf, Madrid Noroeste                 VILLA WITH GARAGE, INDOOR POOL, GYM, SAUNA, TENNIS AND PADDLE TENNIS COURT IN LAS ROZAS.\n\nThe splendid house with more than 3,000 m² is distributed in the main house of 1,050 m² with 10 bedrooms; guest house with 2 bedrooms, 2 bathrooms, living-dining room and kitchen, outdoor garage for 5 vehicles; spa building with indoor pool, sauna, gym and changing rooms; garage building of 460 m² with large capacity for more than 20 cars or other use as office and service; outdoor pool with large gazebo, kitchen and toilet; tennis court, paddle tennis court and basketball court; security guardhouse. All on a plot of 13,700 m². The main house is partially protected by the land, so that its volume is hidden from the outside and only visible from the garden, which gives it total privacy. The property is made up of different rusted volumes. The architectural design is modern, sober and minimalist, with the exterior plastered with oxidized cement with iron sulfate and varnished oxidized steel sheet. The interior has a burnished cement floor and steel plate panels. It is the work of the emblematic architect Manuel Vicens and is one of the best mansions in the area. Among the facilities of the house are underfloor heating, air conditioning and alarm system. Located in the prestigious urbanization Club de Golf de Las Rozas, which has an 18-hole par 70 course, driving range, putting green, swimming pool, clubhouse, restaurant. There is also a tennis and paddle tennis club. Nearby there is a wide range of shopping and leisure facilities, including Las Rozas Village, Heron City and Plaza Norte. In the surroundings, there is a wide range of supermarkets, restaurants, international schools, Puerta de Hierro hospital. Very well connected to Madrid by intercity buses (15 minutes to the Moncloa interchange), suburban train stations and immediate access to the A6.\n\nCan you imagine living here?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     VMO2210004  4,018 m2  12.0        15.0         € 4,000,000    10
Flat for sale in Chueca - Justicia (Madrid)    Chueca - Justicia, Madrid city                EXTERIOR FLAT WITH BALCONIES, LUXURY REFORM AND REMARKABLE LUMINOSITY.\n\nSpectacular flat totally exterior in chamfer, it is a second floor of 94 m² built according to cadastre of which 87 are fully exploited housing, the exquisite luxury reform has been carried out by the architecture studio Euroturner; It has a semicircular living room in chamfer with 3 balconies from floor to ceiling that brings great luminosity to the entire room. Fully equipped kitchen with a large island and decorative wooden panels on the walls that camouflage the sink area and give the room a multipurpose use. Continuing with this paneling structure we find the courtesy toilet. The sleeping area consists of a first exterior bedroom with access from the living room, with en suite bathroom with shower and a floor to ceiling soundproofed balcony. The master bedroom also exterior with large soundproofed window communicates, through a glass panel, with a very large bathroom with freestanding designer bathtub, separate shower and large exterior windows. Fitted closets well dressed. Soundproof windows in the bedrooms. Wooden floors. Marble bathrooms. LED lights. Independent natural gas heating and ducted air conditioning. High ceilings. The apartment has a storage room of about 6 m², elevator with direct access and a large roof terrace for communal use.\n\nCan you imagine living here?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    VM2205050   94 m2     2.0         3.0          € 990,000      10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..

In [175]:
columns = [
    'id', 'sq_mt_built', 'n_rooms', 'n_bathrooms', 'is_exact_address_hidden',
    'floor', 'is_floor_under', 'rent_price', 'is_rent_price_known',
    'buy_price', 'buy_price_by_area', 'is_buy_price_known', 'is_renewal_needed',
    'is_new_development', 'built_year', 'has_central_heating', 'has_individual_heating',
    'has_ac', 'has_fitted_wardrobes', 'has_lift', 'is_exterior', 'has_terrace',
    'has_storage_room', 'energy_certificate', 'has_parking', 'is_parking_included_in_price',
    'parking_price', 'is_orientation_north', 'is_orientation_west', 'is_orientation_south',
    'is_orientation_east', 'neighborhood', 'District', 'HouseType'
]

In [176]:
# List of keywords to check
keywords_housetype = ['flat', 'house', 'building', 'penthouse', 'apartment', 'villa', 'lofts', 'loft', 'land', 'duplex', 'new development', 'homes', 'chalet', 'Piso', 'Property', 'Plot']

# Function to extract house type from heading
def extract_house_type(heading):
    heading_lower = heading.lower()
    for keyword in keywords_housetype:
        if keyword.lower() in heading_lower:
            return keyword.capitalize()
    return 'Unknown'

# Apply the function to the heading column and create the HouseType column
data['HouseType'] = data['heading'].apply(extract_house_type)

# Display the DataFrame
data.head()

,heading,location,content,id,area,n_bedrooms,n_bathrooms,Price,HouseType
0,Flat for sale in calle Treviño (Madrid),"Nuevos Ministerios - Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,34 m2,1.0,1.0,"€ 287,000",Flat
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,187-207 m2,NaN,NaN,"from € 2,917,000",Building
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,49 m2,1.0,1.0,"€ 450,000",Flat
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,148 m2,3.0,4.0,"€ 2,500,000",Flat
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,101 m2,2.0,2.0,"€ 1,359,000",Flat

In [177]:
# Display the rows where HouseType is 'Unknown'
unknown_house_type_rows = data[data['HouseType'] == 'Unknown']
print("Rows with unknown house types: ")
print(len(unknown_house_type_rows))
unknown_house_type_rows

Rows with unknown house types:
2

,heading,location,content,id,area,n_bedrooms,n_bathrooms,Price,HouseType
920,Ground floor for sale with garden in Aravaca,"Aravaca, Madrid Noroeste",We present a ground floor apartment with garde...,VMO2111004,174 m2,4.0,4.0,"€ 1,390,000",Unknown
931,New build luxury construction in Madrid,"Ciudad Jardín, Madrid city",Last properties available in Madrid's Soho.\n\...,ONM2109016,47-284 m2,NaN,NaN,"from € 503,150",Unknown

In [178]:
data.loc[data['HouseType'] == 'Unknown', 'HouseType'] = 'Apartment'

In [179]:
data

,heading,location,content,id,area,n_bedrooms,n_bathrooms,Price,HouseType
0,Flat for sale in calle Treviño (Madrid),"Nuevos Ministerios - Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,34 m2,1.0,1.0,"€ 287,000",Flat
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,187-207 m2,NaN,NaN,"from € 2,917,000",Building
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,49 m2,1.0,1.0,"€ 450,000",Flat
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,148 m2,3.0,4.0,"€ 2,500,000",Flat
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,101 m2,2.0,2.0,"€ 1,359,000",Flat
...,...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,399 m2,6.0,5.0,"€ 2,500,000",Flat
938,Luminous house with terrace for sale in Conde ...,"Conde Orgaz - Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,750 m2,6.0,7.0,"€ 3,100,000",House
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Conde Orgaz - Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,"1,320 m2",5.0,8.0,"€ 3,375,000",Villa
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,480 m2,4.0,4.0,"€ 1,750,000",Loft
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,848 m2,9.0,7.0,"€ 5,800,000",Villa

In [180]:
# Function to clean area column
def clean_area(area_str):
    try:
        # Check if area_str is already float (possibly due to previous conversion)
        if isinstance(area_str, float):
            return None  # Return None for float types

        # Process range case
        if '-' in area_str:
            range_vals = area_str.split('-')
            avg_val = (float(range_vals[0].replace(' m2', '')) + float(range_vals[1].replace(' m2', ''))) / 2
            return avg_val
        else:
            # Otherwise, convert to float after removing ' m2'
            return float(area_str.replace(' m2', ''))
    except (ValueError, AttributeError):
        return None  # Handle any conversion errors gracefully

# Apply cleaning function to area column
data['sq_mt_built'] = data['area'].apply(clean_area)

# Drop the original 'area' column
data.drop(columns=['area'], inplace=True)

# Display the updated DataFrame
data

,heading,location,content,id,n_bedrooms,n_bathrooms,Price,HouseType,sq_mt_built
0,Flat for sale in calle Treviño (Madrid),"Nuevos Ministerios - Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,1.0,1.0,"€ 287,000",Flat,34.0
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,NaN,NaN,"from € 2,917,000",Building,197.0
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,1.0,1.0,"€ 450,000",Flat,49.0
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,3.0,4.0,"€ 2,500,000",Flat,148.0
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,2.0,2.0,"€ 1,359,000",Flat,101.0
...,...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,6.0,5.0,"€ 2,500,000",Flat,399.0
938,Luminous house with terrace for sale in Conde ...,"Conde Orgaz - Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,6.0,7.0,"€ 3,100,000",House,750.0
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Conde Orgaz - Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,5.0,8.0,"€ 3,375,000",Villa,NaN
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,4.0,4.0,"€ 1,750,000",Loft,480.0
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,9.0,7.0,"€ 5,800,000",Villa,848.0

In [181]:
# Remove Euro sign from Price column
# Remove Euro sign and 'from' from Price column
data['buy_price'] = data['Price'].str.replace('€', '').str.replace('from', '').str.strip()
data.drop(columns=['Price'], inplace=True)
# Display the updated DataFrame
data

,heading,location,content,id,n_bedrooms,n_bathrooms,HouseType,sq_mt_built,buy_price
0,Flat for sale in calle Treviño (Madrid),"Nuevos Ministerios - Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,1.0,1.0,Flat,34.0,"287,000"
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,NaN,NaN,Building,197.0,"2,917,000"
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,1.0,1.0,Flat,49.0,"450,000"
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,3.0,4.0,Flat,148.0,"2,500,000"
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,2.0,2.0,Flat,101.0,"1,359,000"
...,...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,6.0,5.0,Flat,399.0,"2,500,000"
938,Luminous house with terrace for sale in Conde ...,"Conde Orgaz - Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,6.0,7.0,House,750.0,"3,100,000"
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Conde Orgaz - Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,5.0,8.0,Villa,NaN,"3,375,000"
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,4.0,4.0,Loft,480.0,"1,750,000"
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,9.0,7.0,Villa,848.0,"5,800,000"

In [182]:
# Remove dash and take text after it using split and strip
data['location'] = data['location'].apply(lambda x: x.split('-')[-1].strip() if '-' in x else x.strip())

In [183]:
data

,heading,location,content,id,n_bedrooms,n_bathrooms,HouseType,sq_mt_built,buy_price
0,Flat for sale in calle Treviño (Madrid),"Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,1.0,1.0,Flat,34.0,"287,000"
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,NaN,NaN,Building,197.0,"2,917,000"
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,1.0,1.0,Flat,49.0,"450,000"
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,3.0,4.0,Flat,148.0,"2,500,000"
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,2.0,2.0,Flat,101.0,"1,359,000"
...,...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,6.0,5.0,Flat,399.0,"2,500,000"
938,Luminous house with terrace for sale in Conde ...,"Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,6.0,7.0,House,750.0,"3,100,000"
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,5.0,8.0,Villa,NaN,"3,375,000"
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,4.0,4.0,Loft,480.0,"1,750,000"
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,9.0,7.0,Villa,848.0,"5,800,000"

In [184]:
# Function to extract built year
def extract_built_year(content):
    if 'built in' in content.lower():
        # Find index of 'built in' and extract year
        idx = content.lower().find('built in') + len('built in')
        year_str = content[idx:idx+4]  # Assuming year format is YYYY
        try:
            year = int(year_str)
            return year
        except ValueError:
            return None
    else:
        return None

# Apply function to create built_year column
data['built_year'] = data['content'].apply(extract_built_year)

# Display the updated DataFrame
data

,heading,location,content,id,n_bedrooms,n_bathrooms,HouseType,sq_mt_built,buy_price,built_year
0,Flat for sale in calle Treviño (Madrid),"Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,1.0,1.0,Flat,34.0,"287,000",NaN
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,NaN,NaN,Building,197.0,"2,917,000",NaN
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,1.0,1.0,Flat,49.0,"450,000",NaN
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,3.0,4.0,Flat,148.0,"2,500,000",NaN
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,2.0,2.0,Flat,101.0,"1,359,000",NaN
...,...,...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,6.0,5.0,Flat,399.0,"2,500,000",NaN
938,Luminous house with terrace for sale in Conde ...,"Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,6.0,7.0,House,750.0,"3,100,000",NaN
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,5.0,8.0,Villa,NaN,"3,375,000",NaN
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,4.0,4.0,Loft,480.0,"1,750,000",NaN
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,9.0,7.0,Villa,848.0,"5,800,000",NaN

In [185]:
data.built_year.value_counts()

built_year
190.0    31
201.0     8
197.0     4
200.0     3
199.0     2
194.0     2
198.0     2
196.0     1
202.0     1
189.0     1
Name: count, dtype: int64

In [186]:
data.built_year.isna().sum()

887

In [187]:
def extract_features(content):
    has_storage_room = 1 if 'storage room' in content.lower() else 0
    has_parking = 1 if 'parking' in content.lower() else 0
    has_terrace = 1 if 'terrace' in content.lower() else 0
    has_fitted_wardrobes = 1 if 'wardrobes' in content.lower() else 0
    return pd.Series([has_storage_room, has_parking, has_terrace, has_fitted_wardrobes], index=['has_storage_room', 'has_parking', 'has_terrace', 'has_fitted_wardrobes'])

# Apply function to create/update columns
data[['has_storage_room', 'has_parking', 'has_terrace', 'has_fitted_wardrobes']] = data['content'].apply(extract_features)

# Display the updated DataFrame
data

,heading,location,content,id,n_bedrooms,n_bathrooms,HouseType,sq_mt_built,buy_price,built_year,has_storage_room,has_parking,has_terrace,has_fitted_wardrobes
0,Flat for sale in calle Treviño (Madrid),"Ríos Rosas, Madrid city",aProperties presents a charming refurbished fl...,VM2407030,1.0,1.0,Flat,34.0,"287,000",NaN,0,0,0,1
1,New building (work) for sale in barrio de Sala...,"Recoletos, Madrid city",There are several luxury residential areas in ...,ONM2407004,NaN,NaN,Building,197.0,"2,917,000",NaN,0,0,1,0
2,Flat for sale in calle Orfila (Madrid),"Almagro, Madrid city","aProperties presents a charming flat, perfect ...",VM2407031,1.0,1.0,Flat,49.0,"450,000",NaN,1,0,0,0
3,Flat for sale in calle Alcalá (Madrid),"Goya, Madrid city",Fabulous flat in a classic building in Alcalá ...,VM2407032,3.0,4.0,Flat,148.0,"2,500,000",NaN,1,0,0,0
4,Flat for sale in Castellana (Madrid),"Castellana, Madrid city","In the most residential area of Castellana, in...",VM2407024,2.0,2.0,Flat,101.0,"1,359,000",NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,Fantastic flat with terrace for sale in Arapil...,"Arapiles, Madrid city",Magnificent stately apartment located in Arapi...,VM1903005,6.0,5.0,Flat,399.0,"2,500,000",NaN,1,0,0,1
938,Luminous house with terrace for sale in Conde ...,"Piovera, Madrid Norte",In the area of Conde Orgaz we find this semi-d...,VMN1812022,6.0,7.0,House,750.0,"3,100,000",NaN,0,0,0,0
939,"Exclusive luxury villa in Conde de Orgaz, for ...","Piovera, Madrid Norte",Spectacular and exclusive villa located in the...,VMN1801019,5.0,8.0,Villa,NaN,"3,375,000",NaN,1,0,0,0
940,Spectacular and exclusive loft in Prosperidad,"Prosperidad, Madrid city",Spectacular and exclusive loft of 450sqm locat...,VM1710006,4.0,4.0,Loft,480.0,"1,750,000",NaN,0,1,1,0
941,Incredible independent villa in El Viso,"El Viso, Madrid city",Superb villa in El Viso of 848sqm of housing a...,VM1705018,9.0,7.0,Villa,848.0,"5,800,000",NaN,1,0,1,0

In [188]:
data.drop(columns=['heading','content'], inplace=True)
data

,location,id,n_bedrooms,n_bathrooms,HouseType,sq_mt_built,buy_price,built_year,has_storage_room,has_parking,has_terrace,has_fitted_wardrobes
0,"Ríos Rosas, Madrid city",VM2407030,1.0,1.0,Flat,34.0,"287,000",NaN,0,0,0,1
1,"Recoletos, Madrid city",ONM2407004,NaN,NaN,Building,197.0,"2,917,000",NaN,0,0,1,0
2,"Almagro, Madrid city",VM2407031,1.0,1.0,Flat,49.0,"450,000",NaN,1,0,0,0
3,"Goya, Madrid city",VM2407032,3.0,4.0,Flat,148.0,"2,500,000",NaN,1,0,0,0
4,"Castellana, Madrid city",VM2407024,2.0,2.0,Flat,101.0,"1,359,000",NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
937,"Arapiles, Madrid city",VM1903005,6.0,5.0,Flat,399.0,"2,500,000",NaN,1,0,0,1
938,"Piovera, Madrid Norte",VMN1812022,6.0,7.0,House,750.0,"3,100,000",NaN,0,0,0,0
939,"Piovera, Madrid Norte",VMN1801019,5.0,8.0,Villa,NaN,"3,375,000",NaN,1,0,0,0
940,"Prosperidad, Madrid city",VM1710006,4.0,4.0,Loft,480.0,"1,750,000",NaN,0,1,1,0
941,"El Viso, Madrid city",VM1705018,9.0,7.0,Villa,848.0,"5,800,000",NaN,1,0,1,0

In [189]:
data.to_csv('modified_aproperties.csv', index=False)